#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define MAX_PROCESSED_EVENTS_SIZE 100000
#define MAX_TRADE_BUFFER_SIZE 100
#define MAX_TRADES_QUEUE_SIZE 100000
#define MAX_EXECUTION_REPORTS_SIZE 100000

#define NUM_DEFAULT_CLIENTS 4

#define CLIENT_PRICE_DISTRIB_MIN (-500)
#define CLIENT_PRICE_DISTRIB_MAX 500
#define CLIENT_BASE_PRICE (100000)

#define CLIENT_QUANTITY_DISTRIB_MIN (-5000)
#define CLIENT_QUANTITY_DISTRIB_MAX 5000
#define CLIENT_BASE_QUANTITY 50000
#define LOCAL_ORDER_BITS 48

#define ORDER_CANCELLATION_FREQ 20
#endif
